# Generated manually because the local virtual environment is not executable on this machine.
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("attendance", "__first__")]
    operations = [
        migrations.CreateModel(name="AnalyticsSnapshot", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField()), ("attendance_score", models.PositiveSmallIntegerField(default=0)), ("task_completion_score", models.PositiveSmallIntegerField(default=0)), ("study_minutes", models.PositiveIntegerField(default=0)), ("productivity_score", models.PositiveSmallIntegerField(default=0)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_snapshots", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-date",)}),
        migrations.CreateModel(name="CareerRoadmap", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("path", models.CharField(choices=[("placement", "Placement"), ("higher_studies", "Higher studies"), ("government", "Government exams"), ("entrepreneurship", "Entrepreneurship")], max_length=20)), ("target_role", models.CharField(max_length=120)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="career_roadmaps", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Notification", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("body", models.CharField(max_length=300)), ("link", models.CharField(blank=True, max_length=300)), ("read_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chronova_notifications", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-created_at",)}),
        migrations.CreateModel(name="VivaSession", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("topic", models.CharField(max_length=180)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="viva_sessions", to=settings.AUTH_USER_MODEL))], options={"ordering": ("-created_at",)}),
        migrations.CreateModel(name="StudyPlan", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("exam_date", models.DateField()), ("daily_hours", models.DecimalField(decimal_places=1, max_digits=4, validators=[MinValueValidator(0.5), MaxValueValidator(16)])), ("units", models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(50)])), ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=10)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="study_plans", to="attendance.subject")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="study_plans", to=settings.AUTH_USER_MODEL))], options={"ordering": ("exam_date", "-created_at")}),
        migrations.CreateModel(name="CareerMilestone", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=180)), ("detail", models.TextField()), ("category", models.CharField(default="skill", max_length=30)), ("position", models.PositiveSmallIntegerField()), ("completed", models.BooleanField(default=False)), ("roadmap", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="planner.careerroadmap"))], options={"ordering": ("position",)}),
        migrations.CreateModel(name="VivaQuestion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("question", models.CharField(max_length=500)), ("suggested_answer", models.TextField()), ("follow_up", models.CharField(max_length=500)), ("difficulty", models.CharField(choices=[("foundation", "Foundation"), ("intermediate", "Intermediate"), ("advanced", "Advanced")], max_length=15)), ("position", models.PositiveSmallIntegerField()), ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="planner.vivasession"))], options={"ordering": ("position",)}),
        migrations.CreateModel(name="StudyPlanItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField()), ("title", models.CharField(max_length=160)), ("unit_number", models.PositiveSmallIntegerField()), ("duration_minutes", models.PositiveSmallIntegerField(validators=[MinValueValidator(15), MaxValueValidator(720)])), ("energy_level", models.CharField(choices=[("high", "High energy"), ("medium", "Medium energy"), ("low", "Low energy")], default="medium", max_length=10)), ("is_revision", models.BooleanField(default=False)), ("completed", models.BooleanField(default=False)), ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="planner.studyplan"))], options={"ordering": ("date", "unit_number")}),
        migrations.CreateModel(name="Assignment", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=160)), ("due_date", models.DateField()), ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=10)), ("notes", models.TextField(blank=True)), ("completed", models.BooleanField(default=False)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("subject", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assignments", to="attendance.subject")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to=settings.AUTH_USER_MODEL))], options={"ordering": ("completed", "due_date")}),
        migrations.AddConstraint(model_name="analyticssnapshot", constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_user_analytics_date")),
        migrations.AddConstraint(model_name="careerroadmap", constraint=models.UniqueConstraint(fields=("user", "path"), name="unique_user_career_path")),
        migrations.AddIndex(model_name="notification", index=models.Index(fields=["user", "read_at", "created_at"], name="planner_not_user_id_d4f0ad_idx")),
        migrations.AddIndex(model_name="studyplan", index=models.Index(fields=["user", "status", "exam_date"], name="planner_stu_user_id_5b17a0_idx")),
        migrations.AddIndex(model_name="studyplanitem", index=models.Index(fields=["plan", "date", "completed"], name="planner_stu_plan_id_43c9f3_idx")),
        migrations.AddIndex(model_name="assignment", index=models.Index(fields=["user", "completed", "due_date"], name="planner_ass_user_id_c1eb45_idx")),
    ]
